// constants/actionTypes.js
export const FETCH_TERMS = 'FETCH_TERMS';
export const CREATE_TERM = 'CREATE_TERM';
export const UPDATE_TERM = 'UPDATE_TERM';
export const DELETE_TERM = 'DELETE_TERM';
export const FETCH_TERM = 'FETCH_TERM';
export const FETCH_COURSES = 'FETCH_COURSES';
export const SUBMIT_COURSES = 'SUBMIT_COURSES';
export const FETCH_STUD_TERM = 'FETCH_STUD_TERM';
export const FETCH_STUD_DETAILS = 'FETCH_STUD_DETAILS';
export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const FETCH_ALL_COURSES = 'FETCH_ALL_COURSES';

export const TOGGLE_COURSE = 'TOGGLE_COURSE';
export const DEACTIVATE_COURSE = 'DEACTIVATE_COURSE';

export const SET_MAX_COUNT = 'SET_MAX_COUNT';   
export const FETCH_DROP_STUDENTS = 'FETCH_DROP_STUDENTS';
export const PUT_DROP_APPLICATION = 'PUT_DROP_APPLICATION';
export const APPLY_FOR_DROP = 'APPLY_FOR_DROP';